const MILLISECOND = 1000;
const MINTOSECOND = 60;
const HOURTOSECOND = MINTOSECOND * 60;
const DAYTOSECOND = HOURTOSECOND * 24;
const WEEKTOSECOND = 604800;
const MONTHTOSECOND = 2628000;

const RESOLUTIONTOSECOND = {
  1: 1 * MINTOSECOND,
  3: 3 * MINTOSECOND,
  5: 5 * MINTOSECOND,
  15: 15 * MINTOSECOND,
  30: 30 * MINTOSECOND,
  60: HOURTOSECOND,
  120: 2 * HOURTOSECOND,
  240: 4 * HOURTOSECOND,
  "1D": DAYTOSECOND,
  "1W": WEEKTOSECOND,
  "1M": MONTHTOSECOND,
};

export const resolutionGap = (resolution) => {
  return RESOLUTIONTOSECOND[resolution];
};
